# Generated by Django 2.1.10 on 2019-07-29 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SID', models.IntegerField()),
                ('name', models.CharField(max_length=20)),
                ('test', models.CharField(max_length=40)),
                ('score_chinese', models.IntegerField()),
                ('score_math', models.IntegerField()),
                ('score_English', models.IntegerField()),
                ('score_physics', models.IntegerField()),
                ('score_chemisty', models.IntegerField()),
            ],
        ),
    ]
